SET IDENTITY_INSERT Address ON;
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (1,'mazowieckie','Warszawa','Kazury',90,null,'53-969');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (2,'mazowieckie','Warszawa','Stryjeńskich',43,null,'35-273');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (3,'mazowieckie','Warszawa','Marszałkowska',99,null,'99-820');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (4,'mazowieckie','Warszawa','Kazury',89,78,'40-647');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (5,'mazowieckie','Warszawa','Kazury',82,74,'33-051');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (6,'mazowieckie','Warszawa','Kazury',49,36,'18-884');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (7,'mazowieckie','Warszawa','Kazury',40,49,'69-100');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (8,'mazowieckie','Warszawa','Kazury',21,63,'58-544');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (9,'mazowieckie','Warszawa','Kazury',66,36,'71-009');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (10,'mazowieckie','Warszawa','Kazury',58,21,'30-974');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (11,'mazowieckie','Warszawa','Kazury',7,95,'87-183');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (12,'mazowieckie','Warszawa','Kazury',16,91,'78-783');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (13,'mazowieckie','Warszawa','Kazury',73,31,'81-063');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (14,'mazowieckie','Warszawa','Kazury',93,8,'78-381');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (15,'mazowieckie','Warszawa','Kazury',92,61,'36-661');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (16,'mazowieckie','Warszawa','Kazury',96,88,'00-553');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (17,'mazowieckie','Warszawa','Kazury',93,25,'14-505');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (18,'mazowieckie','Warszawa','Kazury',36,36,'26-507');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (19,'mazowieckie','Warszawa','Kazury',11,8,'23-777');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (20,'mazowieckie','Warszawa','Kazury',77,22,'57-162');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (21,'mazowieckie','Warszawa','Kazury',80,47,'82-498');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (22,'mazowieckie','Warszawa','Kazury',22,6,'61-971');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (23,'mazowieckie','Warszawa','Kazury',79,5,'01-452');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (24,'mazowieckie','Warszawa','Kazury',41,40,'91-336');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (25,'mazowieckie','Warszawa','Kazury',3,1,'69-641');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (26,'mazowieckie','Warszawa','Kazury',41,55,'10-255');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (27,'mazowieckie','Warszawa','Kazury',56,37,'14-991');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (28,'mazowieckie','Warszawa','Kazury',18,84,'97-923');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (29,'mazowieckie','Warszawa','Kazury',58,16,'25-621');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (30,'mazowieckie','Warszawa','Kazury',51,42,'27-582');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (31,'mazowieckie','Warszawa','Kazury',73,82,'59-867');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (32,'mazowieckie','Warszawa','Kazury',59,84,'84-845');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (33,'mazowieckie','Warszawa','Kazury',22,7,'87-323');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (34,'mazowieckie','Warszawa','Kazury',54,51,'08-901');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (35,'mazowieckie','Warszawa','Kazury',88,91,'50-645');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (36,'mazowieckie','Warszawa','Kazury',25,97,'36-302');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (37,'mazowieckie','Warszawa','Kazury',4,94,'73-515');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (38,'mazowieckie','Warszawa','Kazury',88,44,'79-995');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (39,'mazowieckie','Warszawa','Kazury',51,15,'92-255');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (40,'mazowieckie','Warszawa','Kazury',90,68,'89-604');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (41,'mazowieckie','Warszawa','Kazury',73,7,'01-235');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (42,'mazowieckie','Warszawa','Kazury',29,24,'64-271');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (43,'mazowieckie','Warszawa','Kazury',73,12,'60-113');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (44,'mazowieckie','Warszawa','Kazury',51,24,'79-909');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (45,'mazowieckie','Warszawa','Kazury',91,48,'94-282');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (46,'mazowieckie','Warszawa','Kazury',51,19,'13-730');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (47,'mazowieckie','Warszawa','Kazury',23,99,'10-416');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (48,'mazowieckie','Warszawa','Kazury',71,7,'97-312');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (49,'mazowieckie','Warszawa','Kazury',5,63,'58-709');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (50,'mazowieckie','Warszawa','Kazury',1,9,'03-480');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (51,'mazowieckie','Warszawa','Kazury',47,34,'31-368');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (52,'mazowieckie','Warszawa','Kazury',29,20,'65-579');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (53,'mazowieckie','Warszawa','Kazury',70,1,'89-975');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (54,'mazowieckie','Warszawa','Stryjeńskich',36,77,'21-846');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (55,'mazowieckie','Warszawa','Stryjeńskich',17,54,'76-287');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (56,'mazowieckie','Warszawa','Stryjeńskich',81,6,'17-326');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (57,'mazowieckie','Warszawa','Stryjeńskich',63,15,'38-057');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (58,'mazowieckie','Warszawa','Stryjeńskich',6,54,'34-878');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (59,'mazowieckie','Warszawa','Stryjeńskich',36,88,'54-084');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (60,'mazowieckie','Warszawa','Stryjeńskich',21,44,'70-704');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (61,'mazowieckie','Warszawa','Stryjeńskich',40,85,'41-860');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (62,'mazowieckie','Warszawa','Stryjeńskich',18,70,'85-298');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (63,'mazowieckie','Warszawa','Stryjeńskich',69,17,'65-030');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (64,'mazowieckie','Warszawa','Stryjeńskich',51,38,'60-345');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (65,'mazowieckie','Warszawa','Stryjeńskich',89,81,'57-788');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (66,'mazowieckie','Warszawa','Stryjeńskich',57,83,'04-197');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (67,'mazowieckie','Warszawa','Stryjeńskich',9,85,'10-404');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (68,'mazowieckie','Warszawa','Stryjeńskich',27,35,'50-088');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (69,'mazowieckie','Warszawa','Stryjeńskich',80,60,'02-733');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (70,'mazowieckie','Warszawa','Stryjeńskich',29,20,'23-941');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (71,'mazowieckie','Warszawa','Stryjeńskich',4,21,'28-356');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (72,'mazowieckie','Warszawa','Stryjeńskich',7,27,'31-156');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (73,'mazowieckie','Warszawa','Stryjeńskich',60,86,'65-293');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (74,'mazowieckie','Warszawa','Stryjeńskich',14,25,'42-385');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (75,'mazowieckie','Warszawa','Stryjeńskich',21,5,'40-788');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (76,'mazowieckie','Warszawa','Stryjeńskich',24,97,'83-134');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (77,'mazowieckie','Warszawa','Stryjeńskich',90,72,'41-914');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (78,'mazowieckie','Warszawa','Stryjeńskich',39,1,'13-362');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (79,'mazowieckie','Warszawa','Stryjeńskich',61,74,'41-412');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (80,'mazowieckie','Warszawa','Stryjeńskich',56,17,'18-005');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (81,'mazowieckie','Warszawa','Stryjeńskich',4,78,'12-566');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (82,'mazowieckie','Warszawa','Stryjeńskich',92,76,'69-091');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (83,'mazowieckie','Warszawa','Stryjeńskich',36,98,'09-104');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (84,'mazowieckie','Warszawa','Stryjeńskich',97,40,'13-751');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (85,'mazowieckie','Warszawa','Stryjeńskich',27,16,'67-526');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (86,'mazowieckie','Warszawa','Stryjeńskich',36,16,'85-649');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (87,'mazowieckie','Warszawa','Stryjeńskich',74,46,'50-426');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (88,'mazowieckie','Warszawa','Stryjeńskich',30,4,'38-495');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (89,'mazowieckie','Warszawa','Stryjeńskich',83,43,'97-142');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (90,'mazowieckie','Warszawa','Stryjeńskich',41,48,'13-193');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (91,'mazowieckie','Warszawa','Stryjeńskich',26,35,'53-868');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (92,'mazowieckie','Warszawa','Stryjeńskich',98,57,'84-788');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (93,'mazowieckie','Warszawa','Stryjeńskich',80,21,'95-259');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (94,'mazowieckie','Warszawa','Stryjeńskich',84,99,'96-551');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (95,'mazowieckie','Warszawa','Stryjeńskich',99,13,'34-452');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (96,'mazowieckie','Warszawa','Stryjeńskich',96,61,'77-253');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (97,'mazowieckie','Warszawa','Stryjeńskich',89,18,'54-225');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (98,'mazowieckie','Warszawa','Stryjeńskich',64,93,'93-757');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (99,'mazowieckie','Warszawa','Stryjeńskich',1,44,'56-984');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (100,'mazowieckie','Warszawa','Stryjeńskich',87,37,'53-986');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (101,'mazowieckie','Warszawa','Stryjeńskich',74,59,'16-246');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (102,'mazowieckie','Warszawa','Stryjeńskich',87,8,'47-829');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (103,'mazowieckie','Warszawa','Stryjeńskich',69,79,'37-343');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (104,'mazowieckie','Warszawa','Marszałkowska',89,93,'40-653');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (105,'mazowieckie','Warszawa','Marszałkowska',35,15,'38-362');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (106,'mazowieckie','Warszawa','Marszałkowska',80,27,'90-124');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (107,'mazowieckie','Warszawa','Marszałkowska',91,32,'77-455');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (108,'mazowieckie','Warszawa','Marszałkowska',20,83,'85-663');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (109,'mazowieckie','Warszawa','Marszałkowska',93,16,'30-507');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (110,'mazowieckie','Warszawa','Marszałkowska',84,39,'03-306');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (111,'mazowieckie','Warszawa','Marszałkowska',28,88,'72-461');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (112,'mazowieckie','Warszawa','Marszałkowska',38,7,'87-776');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (113,'mazowieckie','Warszawa','Marszałkowska',66,95,'85-269');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (114,'mazowieckie','Warszawa','Marszałkowska',65,22,'21-983');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (115,'mazowieckie','Warszawa','Marszałkowska',94,62,'29-613');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (116,'mazowieckie','Warszawa','Marszałkowska',18,50,'09-437');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (117,'mazowieckie','Warszawa','Marszałkowska',64,40,'44-505');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (118,'mazowieckie','Warszawa','Marszałkowska',22,62,'75-992');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (119,'mazowieckie','Warszawa','Marszałkowska',97,72,'63-481');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (120,'mazowieckie','Warszawa','Marszałkowska',92,71,'62-291');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (121,'mazowieckie','Warszawa','Marszałkowska',65,8,'88-561');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (122,'mazowieckie','Warszawa','Marszałkowska',76,27,'76-555');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (123,'mazowieckie','Warszawa','Marszałkowska',43,71,'70-997');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (124,'mazowieckie','Warszawa','Marszałkowska',85,57,'94-743');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (125,'mazowieckie','Warszawa','Marszałkowska',63,89,'28-140');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (126,'mazowieckie','Warszawa','Marszałkowska',34,48,'85-818');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (127,'mazowieckie','Warszawa','Marszałkowska',63,6,'85-309');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (128,'mazowieckie','Warszawa','Marszałkowska',79,7,'01-071');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (129,'mazowieckie','Warszawa','Marszałkowska',44,78,'69-586');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (130,'mazowieckie','Warszawa','Marszałkowska',70,58,'40-254');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (131,'mazowieckie','Warszawa','Marszałkowska',75,38,'45-771');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (132,'mazowieckie','Warszawa','Marszałkowska',82,43,'27-977');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (133,'mazowieckie','Warszawa','Marszałkowska',48,74,'63-514');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (134,'mazowieckie','Warszawa','Marszałkowska',57,96,'46-768');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (135,'mazowieckie','Warszawa','Marszałkowska',8,74,'43-593');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (136,'mazowieckie','Warszawa','Marszałkowska',6,77,'89-185');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (137,'mazowieckie','Warszawa','Marszałkowska',86,46,'63-701');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (138,'mazowieckie','Warszawa','Marszałkowska',14,96,'95-506');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (139,'mazowieckie','Warszawa','Marszałkowska',38,40,'65-748');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (140,'mazowieckie','Warszawa','Marszałkowska',71,2,'23-450');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (141,'mazowieckie','Warszawa','Marszałkowska',59,91,'22-418');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (142,'mazowieckie','Warszawa','Marszałkowska',65,69,'02-951');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (143,'mazowieckie','Warszawa','Marszałkowska',94,57,'95-549');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (144,'mazowieckie','Warszawa','Marszałkowska',7,44,'38-311');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (145,'mazowieckie','Warszawa','Marszałkowska',60,26,'54-420');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (146,'mazowieckie','Warszawa','Marszałkowska',52,96,'40-894');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (147,'mazowieckie','Warszawa','Marszałkowska',32,8,'53-318');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (148,'mazowieckie','Warszawa','Marszałkowska',74,55,'54-895');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (149,'mazowieckie','Warszawa','Marszałkowska',99,1,'28-658');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (150,'mazowieckie','Warszawa','Marszałkowska',70,53,'98-634');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (151,'mazowieckie','Warszawa','Marszałkowska',68,52,'41-921');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (152,'mazowieckie','Warszawa','Marszałkowska',56,79,'17-525');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (153,'mazowieckie','Warszawa','Marszałkowska',83,28,'03-254');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (154,'mazowieckie','Warszawa','Złota',85,62,'34-691');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (155,'mazowieckie','Warszawa','Złota',49,17,'79-700');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (156,'mazowieckie','Warszawa','Złota',69,30,'57-775');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (157,'mazowieckie','Warszawa','Złota',81,94,'13-937');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (158,'mazowieckie','Warszawa','Złota',95,99,'77-757');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (159,'mazowieckie','Warszawa','Złota',43,51,'20-111');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (160,'mazowieckie','Warszawa','Złota',34,14,'62-170');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (161,'mazowieckie','Warszawa','Złota',3,69,'37-361');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (162,'mazowieckie','Warszawa','Złota',96,38,'52-265');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (163,'mazowieckie','Warszawa','Złota',51,50,'28-448');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (164,'mazowieckie','Warszawa','Złota',3,28,'14-323');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (165,'mazowieckie','Warszawa','Złota',97,43,'13-501');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (166,'mazowieckie','Warszawa','Złota',88,73,'67-563');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (167,'mazowieckie','Warszawa','Złota',41,96,'60-311');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (168,'mazowieckie','Warszawa','Złota',69,50,'89-272');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (169,'mazowieckie','Warszawa','Złota',84,37,'12-268');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (170,'mazowieckie','Warszawa','Złota',76,41,'55-116');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (171,'mazowieckie','Warszawa','Złota',52,50,'91-435');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (172,'mazowieckie','Warszawa','Złota',42,46,'12-355');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (173,'mazowieckie','Warszawa','Złota',76,61,'92-609');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (174,'mazowieckie','Warszawa','Złota',97,56,'15-322');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (175,'mazowieckie','Warszawa','Złota',56,44,'26-139');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (176,'mazowieckie','Warszawa','Złota',63,81,'30-213');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (177,'mazowieckie','Warszawa','Złota',55,74,'01-303');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (178,'mazowieckie','Warszawa','Złota',76,97,'86-886');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (179,'mazowieckie','Warszawa','Złota',53,66,'00-371');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (180,'mazowieckie','Warszawa','Złota',83,69,'05-836');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (181,'mazowieckie','Warszawa','Złota',44,14,'53-156');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (182,'mazowieckie','Warszawa','Złota',64,6,'64-358');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (183,'mazowieckie','Warszawa','Złota',53,30,'77-782');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (184,'mazowieckie','Warszawa','Złota',17,41,'85-802');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (185,'mazowieckie','Warszawa','Złota',7,24,'47-872');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (186,'mazowieckie','Warszawa','Złota',45,75,'08-400');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (187,'mazowieckie','Warszawa','Złota',99,50,'23-845');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (188,'mazowieckie','Warszawa','Złota',60,93,'86-516');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (189,'mazowieckie','Warszawa','Złota',78,16,'83-146');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (190,'mazowieckie','Warszawa','Złota',9,80,'47-932');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (191,'mazowieckie','Warszawa','Złota',52,68,'69-124');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (192,'mazowieckie','Warszawa','Złota',11,7,'52-917');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (193,'mazowieckie','Warszawa','Złota',55,63,'16-555');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (194,'mazowieckie','Warszawa','Złota',32,17,'48-856');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (195,'mazowieckie','Warszawa','Złota',67,92,'05-141');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (196,'mazowieckie','Warszawa','Złota',24,53,'39-998');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (197,'mazowieckie','Warszawa','Złota',29,63,'59-161');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (198,'mazowieckie','Warszawa','Złota',6,83,'72-702');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (199,'mazowieckie','Warszawa','Złota',52,99,'61-464');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (200,'mazowieckie','Warszawa','Złota',58,20,'36-738');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (201,'mazowieckie','Warszawa','Złota',33,77,'87-788');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (202,'mazowieckie','Warszawa','Złota',25,54,'80-842');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (203,'mazowieckie','Warszawa','Złota',52,48,'56-523');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (204,'mazowieckie','Warszawa','Kupiecka',15,90,'71-707');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (205,'mazowieckie','Warszawa','Kupiecka',33,74,'45-662');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (206,'mazowieckie','Warszawa','Kupiecka',52,32,'13-624');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (207,'mazowieckie','Warszawa','Kupiecka',10,93,'24-704');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (208,'mazowieckie','Warszawa','Kupiecka',80,72,'44-696');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (209,'mazowieckie','Warszawa','Kupiecka',33,30,'89-212');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (210,'mazowieckie','Warszawa','Kupiecka',38,37,'69-509');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (211,'mazowieckie','Warszawa','Kupiecka',78,65,'34-261');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (212,'mazowieckie','Warszawa','Kupiecka',13,87,'84-422');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (213,'mazowieckie','Warszawa','Kupiecka',55,42,'20-197');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (214,'mazowieckie','Warszawa','Kupiecka',28,11,'94-606');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (215,'mazowieckie','Warszawa','Kupiecka',1,55,'23-519');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (216,'mazowieckie','Warszawa','Kupiecka',85,3,'67-991');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (217,'mazowieckie','Warszawa','Kupiecka',5,93,'26-176');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (218,'mazowieckie','Warszawa','Kupiecka',94,63,'78-484');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (219,'mazowieckie','Warszawa','Kupiecka',46,43,'08-135');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (220,'mazowieckie','Warszawa','Kupiecka',44,20,'05-628');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (221,'mazowieckie','Warszawa','Kupiecka',17,56,'95-120');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (222,'mazowieckie','Warszawa','Kupiecka',47,62,'01-960');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (223,'mazowieckie','Warszawa','Kupiecka',57,28,'58-238');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (224,'mazowieckie','Warszawa','Kupiecka',8,44,'60-207');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (225,'mazowieckie','Warszawa','Kupiecka',16,15,'33-878');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (226,'mazowieckie','Warszawa','Kupiecka',12,74,'06-668');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (227,'mazowieckie','Warszawa','Kupiecka',26,16,'78-176');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (228,'mazowieckie','Warszawa','Kupiecka',80,37,'86-782');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (229,'mazowieckie','Warszawa','Kupiecka',25,33,'34-254');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (230,'mazowieckie','Warszawa','Kupiecka',37,54,'74-797');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (231,'mazowieckie','Warszawa','Kupiecka',33,28,'15-977');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (232,'mazowieckie','Warszawa','Kupiecka',48,70,'78-392');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (233,'mazowieckie','Warszawa','Kupiecka',14,59,'35-170');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (234,'mazowieckie','Warszawa','Kupiecka',32,54,'01-981');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (235,'mazowieckie','Warszawa','Kupiecka',80,49,'77-071');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (236,'mazowieckie','Warszawa','Kupiecka',57,55,'24-249');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (237,'mazowieckie','Warszawa','Kupiecka',9,80,'39-105');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (238,'mazowieckie','Warszawa','Kupiecka',23,58,'27-336');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (239,'mazowieckie','Warszawa','Kupiecka',26,74,'36-863');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (240,'mazowieckie','Warszawa','Kupiecka',56,97,'18-230');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (241,'mazowieckie','Warszawa','Kupiecka',10,51,'12-857');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (242,'mazowieckie','Warszawa','Kupiecka',45,64,'69-576');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (243,'mazowieckie','Warszawa','Kupiecka',53,29,'76-191');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (244,'mazowieckie','Warszawa','Kupiecka',64,41,'02-314');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (245,'mazowieckie','Warszawa','Kupiecka',58,82,'39-264');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (246,'mazowieckie','Warszawa','Kupiecka',9,31,'44-348');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (247,'mazowieckie','Warszawa','Kupiecka',77,99,'40-068');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (248,'mazowieckie','Warszawa','Kupiecka',56,33,'44-904');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (249,'mazowieckie','Warszawa','Kupiecka',8,29,'22-600');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (250,'mazowieckie','Warszawa','Kupiecka',4,16,'48-638');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (251,'mazowieckie','Warszawa','Kupiecka',43,17,'69-531');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (252,'mazowieckie','Warszawa','Kupiecka',78,58,'78-748');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (253,'mazowieckie','Warszawa','Kupiecka',12,8,'74-726');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (254,'mazowieckie','Warszawa','Długa',84,71,'84-648');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (255,'mazowieckie','Warszawa','Długa',25,95,'00-850');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (256,'mazowieckie','Warszawa','Długa',73,41,'19-729');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (257,'mazowieckie','Warszawa','Długa',26,80,'73-801');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (258,'mazowieckie','Warszawa','Długa',68,61,'56-635');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (259,'mazowieckie','Warszawa','Długa',12,92,'13-152');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (260,'mazowieckie','Warszawa','Długa',39,81,'90-314');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (261,'mazowieckie','Warszawa','Długa',94,62,'14-178');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (262,'mazowieckie','Warszawa','Długa',57,55,'96-084');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (263,'mazowieckie','Warszawa','Długa',87,8,'01-036');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (264,'mazowieckie','Warszawa','Długa',16,72,'97-164');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (265,'mazowieckie','Warszawa','Długa',44,96,'50-647');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (266,'mazowieckie','Warszawa','Długa',44,26,'06-794');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (267,'mazowieckie','Warszawa','Długa',11,1,'89-203');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (268,'mazowieckie','Warszawa','Długa',28,94,'73-614');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (269,'mazowieckie','Warszawa','Długa',10,36,'21-459');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (270,'mazowieckie','Warszawa','Długa',15,32,'70-859');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (271,'mazowieckie','Warszawa','Długa',15,74,'92-678');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (272,'mazowieckie','Warszawa','Długa',12,87,'34-069');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (273,'mazowieckie','Warszawa','Długa',10,84,'09-618');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (274,'mazowieckie','Warszawa','Długa',43,67,'82-829');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (275,'mazowieckie','Warszawa','Długa',83,14,'17-482');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (276,'mazowieckie','Warszawa','Długa',23,70,'05-988');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (277,'mazowieckie','Warszawa','Długa',9,49,'13-960');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (278,'mazowieckie','Warszawa','Długa',41,34,'25-666');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (279,'mazowieckie','Warszawa','Długa',5,25,'70-286');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (280,'mazowieckie','Warszawa','Długa',15,52,'19-625');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (281,'mazowieckie','Warszawa','Długa',38,44,'96-882');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (282,'mazowieckie','Warszawa','Długa',97,96,'66-422');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (283,'mazowieckie','Warszawa','Długa',92,33,'73-526');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (284,'mazowieckie','Warszawa','Długa',18,95,'56-033');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (285,'mazowieckie','Warszawa','Długa',51,55,'77-697');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (286,'mazowieckie','Warszawa','Długa',45,30,'10-101');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (287,'mazowieckie','Warszawa','Długa',65,23,'88-978');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (288,'mazowieckie','Warszawa','Długa',53,37,'41-498');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (289,'mazowieckie','Warszawa','Długa',71,57,'33-185');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (290,'mazowieckie','Warszawa','Długa',53,33,'78-229');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (291,'mazowieckie','Warszawa','Długa',38,89,'18-438');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (292,'mazowieckie','Warszawa','Długa',13,5,'27-884');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (293,'mazowieckie','Warszawa','Długa',25,10,'75-441');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (294,'mazowieckie','Warszawa','Długa',53,45,'94-437');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (295,'mazowieckie','Warszawa','Długa',29,5,'59-632');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (296,'mazowieckie','Warszawa','Długa',50,82,'26-234');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (297,'mazowieckie','Warszawa','Długa',94,44,'14-424');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (298,'mazowieckie','Warszawa','Długa',39,31,'25-899');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (299,'mazowieckie','Warszawa','Długa',76,91,'97-543');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (300,'mazowieckie','Warszawa','Długa',46,69,'06-366');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (301,'mazowieckie','Warszawa','Długa',23,30,'43-063');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (302,'mazowieckie','Warszawa','Długa',12,10,'17-692');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (303,'mazowieckie','Warszawa','Długa',18,44,'16-224');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (304,'mazowieckie','Warszawa','Zamkowa',90,13,'93-143');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (305,'mazowieckie','Warszawa','Zamkowa',22,43,'48-736');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (306,'mazowieckie','Warszawa','Zamkowa',55,91,'07-868');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (307,'mazowieckie','Warszawa','Zamkowa',15,42,'65-993');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (308,'mazowieckie','Warszawa','Zamkowa',23,67,'35-610');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (309,'mazowieckie','Warszawa','Zamkowa',62,52,'02-842');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (310,'mazowieckie','Warszawa','Zamkowa',3,83,'88-698');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (311,'mazowieckie','Warszawa','Zamkowa',57,86,'36-543');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (312,'mazowieckie','Warszawa','Zamkowa',64,71,'48-238');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (313,'mazowieckie','Warszawa','Zamkowa',54,32,'22-090');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (314,'mazowieckie','Warszawa','Zamkowa',95,17,'38-963');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (315,'mazowieckie','Warszawa','Zamkowa',99,79,'89-060');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (316,'mazowieckie','Warszawa','Zamkowa',84,29,'92-885');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (317,'mazowieckie','Warszawa','Zamkowa',48,95,'68-629');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (318,'mazowieckie','Warszawa','Zamkowa',3,11,'57-835');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (319,'mazowieckie','Warszawa','Zamkowa',94,68,'68-363');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (320,'mazowieckie','Warszawa','Zamkowa',64,3,'59-687');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (321,'mazowieckie','Warszawa','Zamkowa',21,67,'00-456');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (322,'mazowieckie','Warszawa','Zamkowa',16,90,'19-923');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (323,'mazowieckie','Warszawa','Zamkowa',41,80,'99-089');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (324,'mazowieckie','Warszawa','Zamkowa',20,42,'83-596');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (325,'mazowieckie','Warszawa','Zamkowa',98,91,'70-645');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (326,'mazowieckie','Warszawa','Zamkowa',25,81,'16-143');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (327,'mazowieckie','Warszawa','Zamkowa',43,26,'47-762');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (328,'mazowieckie','Warszawa','Zamkowa',51,74,'62-154');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (329,'mazowieckie','Warszawa','Zamkowa',29,6,'08-995');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (330,'mazowieckie','Warszawa','Zamkowa',86,36,'95-459');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (331,'mazowieckie','Warszawa','Zamkowa',80,30,'73-687');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (332,'mazowieckie','Warszawa','Zamkowa',84,96,'14-262');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (333,'mazowieckie','Warszawa','Zamkowa',53,5,'62-795');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (334,'mazowieckie','Warszawa','Zamkowa',42,68,'74-857');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (335,'mazowieckie','Warszawa','Zamkowa',74,1,'83-633');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (336,'mazowieckie','Warszawa','Zamkowa',13,73,'59-590');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (337,'mazowieckie','Warszawa','Zamkowa',93,11,'29-747');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (338,'mazowieckie','Warszawa','Zamkowa',87,28,'42-145');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (339,'mazowieckie','Warszawa','Zamkowa',17,33,'02-129');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (340,'mazowieckie','Warszawa','Zamkowa',54,92,'91-086');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (341,'mazowieckie','Warszawa','Zamkowa',2,98,'02-126');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (342,'mazowieckie','Warszawa','Zamkowa',90,73,'71-649');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (343,'mazowieckie','Warszawa','Zamkowa',1,67,'87-605');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (344,'mazowieckie','Warszawa','Zamkowa',53,52,'71-328');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (345,'mazowieckie','Warszawa','Zamkowa',62,73,'45-215');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (346,'mazowieckie','Warszawa','Zamkowa',84,75,'44-857');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (347,'mazowieckie','Warszawa','Zamkowa',28,30,'73-480');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (348,'mazowieckie','Warszawa','Zamkowa',14,30,'77-066');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (349,'mazowieckie','Warszawa','Zamkowa',69,83,'73-319');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (350,'mazowieckie','Warszawa','Zamkowa',52,17,'80-230');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (351,'mazowieckie','Warszawa','Zamkowa',46,4,'11-358');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (352,'mazowieckie','Warszawa','Zamkowa',33,87,'89-415');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (353,'mazowieckie','Warszawa','Zamkowa',5,11,'57-454');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (354,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',43,46,'07-143');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (355,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',57,5,'91-594');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (356,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',31,50,'28-279');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (357,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',62,95,'69-123');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (358,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',42,56,'12-105');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (359,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',71,44,'80-380');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (360,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',52,86,'78-549');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (361,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',22,28,'08-268');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (362,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',65,69,'16-975');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (363,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',91,28,'25-115');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (364,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',74,90,'74-812');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (365,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',43,88,'19-560');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (366,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',80,81,'23-035');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (367,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',3,38,'64-064');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (368,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',39,58,'27-224');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (369,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',70,59,'62-553');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (370,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',83,34,'36-221');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (371,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',86,64,'43-145');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (372,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',98,28,'31-570');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (373,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',72,91,'30-273');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (374,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',77,57,'97-683');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (375,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',3,65,'68-449');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (376,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',42,89,'31-873');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (377,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',25,30,'64-301');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (378,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',53,4,'23-039');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (379,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',39,21,'28-260');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (380,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',99,80,'84-328');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (381,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',54,15,'00-624');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (382,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',65,23,'01-255');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (383,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',53,76,'08-554');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (384,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',38,55,'61-456');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (385,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',78,50,'29-812');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (386,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',95,84,'98-581');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (387,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',16,71,'96-250');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (388,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',99,36,'58-199');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (389,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',80,11,'90-121');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (390,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',35,54,'89-518');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (391,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',63,1,'27-379');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (392,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',71,90,'92-882');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (393,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',43,6,'69-835');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (394,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',34,48,'83-587');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (395,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',5,64,'56-414');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (396,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',82,74,'05-662');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (397,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',8,34,'79-472');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (398,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',49,29,'81-608');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (399,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',13,19,'66-971');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (400,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',90,28,'11-418');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (401,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',89,29,'24-467');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (402,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',87,40,'46-048');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (403,'mazowieckie','Warszawa','Komisji Edukacji Narodowej',98,90,'43-873');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (404,'mazowieckie','Warszawa','Puławska',30,3,'81-812');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (405,'mazowieckie','Warszawa','Puławska',64,94,'64-192');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (406,'mazowieckie','Warszawa','Puławska',43,3,'13-295');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (407,'mazowieckie','Warszawa','Puławska',21,20,'40-027');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (408,'mazowieckie','Warszawa','Puławska',19,82,'98-677');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (409,'mazowieckie','Warszawa','Puławska',50,54,'87-691');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (410,'mazowieckie','Warszawa','Puławska',96,79,'87-419');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (411,'mazowieckie','Warszawa','Puławska',56,11,'60-648');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (412,'mazowieckie','Warszawa','Puławska',25,55,'69-648');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (413,'mazowieckie','Warszawa','Puławska',71,22,'47-269');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (414,'mazowieckie','Warszawa','Puławska',59,21,'67-393');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (415,'mazowieckie','Warszawa','Puławska',67,39,'15-519');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (416,'mazowieckie','Warszawa','Puławska',77,39,'71-520');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (417,'mazowieckie','Warszawa','Puławska',82,79,'99-344');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (418,'mazowieckie','Warszawa','Puławska',79,52,'78-971');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (419,'mazowieckie','Warszawa','Puławska',82,22,'48-363');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (420,'mazowieckie','Warszawa','Puławska',83,47,'81-457');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (421,'mazowieckie','Warszawa','Puławska',74,68,'77-198');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (422,'mazowieckie','Warszawa','Puławska',9,15,'65-043');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (423,'mazowieckie','Warszawa','Puławska',22,9,'82-424');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (424,'mazowieckie','Warszawa','Puławska',63,13,'44-358');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (425,'mazowieckie','Warszawa','Puławska',74,57,'14-641');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (426,'mazowieckie','Warszawa','Puławska',27,28,'41-015');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (427,'mazowieckie','Warszawa','Puławska',33,60,'95-907');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (428,'mazowieckie','Warszawa','Puławska',93,39,'46-635');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (429,'mazowieckie','Warszawa','Puławska',42,50,'29-331');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (430,'mazowieckie','Warszawa','Puławska',34,17,'40-707');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (431,'mazowieckie','Warszawa','Puławska',26,26,'44-538');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (432,'mazowieckie','Warszawa','Puławska',65,77,'67-690');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (433,'mazowieckie','Warszawa','Puławska',58,27,'51-274');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (434,'mazowieckie','Warszawa','Puławska',62,74,'17-540');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (435,'mazowieckie','Warszawa','Puławska',26,28,'46-030');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (436,'mazowieckie','Warszawa','Puławska',65,83,'87-630');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (437,'mazowieckie','Warszawa','Puławska',96,70,'60-591');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (438,'mazowieckie','Warszawa','Puławska',87,41,'62-097');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (439,'mazowieckie','Warszawa','Puławska',20,53,'57-130');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (440,'mazowieckie','Warszawa','Puławska',54,19,'94-773');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (441,'mazowieckie','Warszawa','Puławska',38,87,'31-737');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (442,'mazowieckie','Warszawa','Puławska',73,1,'29-568');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (443,'mazowieckie','Warszawa','Puławska',51,3,'71-149');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (444,'mazowieckie','Warszawa','Puławska',92,90,'26-500');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (445,'mazowieckie','Warszawa','Puławska',73,92,'13-141');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (446,'mazowieckie','Warszawa','Puławska',54,53,'83-785');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (447,'mazowieckie','Warszawa','Puławska',37,54,'67-861');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (448,'mazowieckie','Warszawa','Puławska',68,4,'72-897');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (449,'mazowieckie','Warszawa','Puławska',10,95,'92-779');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (450,'mazowieckie','Warszawa','Puławska',99,20,'10-386');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (451,'mazowieckie','Warszawa','Puławska',96,16,'09-404');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (452,'mazowieckie','Warszawa','Puławska',77,82,'78-972');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (453,'mazowieckie','Warszawa','Puławska',15,50,'87-336');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (454,'mazowieckie','Warszawa','Lanciego',45,75,'82-517');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (455,'mazowieckie','Warszawa','Lanciego',88,39,'15-368');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (456,'mazowieckie','Warszawa','Lanciego',89,19,'47-488');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (457,'mazowieckie','Warszawa','Lanciego',39,25,'18-377');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (458,'mazowieckie','Warszawa','Lanciego',86,25,'09-578');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (459,'mazowieckie','Warszawa','Lanciego',30,61,'37-852');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (460,'mazowieckie','Warszawa','Lanciego',45,99,'90-393');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (461,'mazowieckie','Warszawa','Lanciego',63,3,'97-245');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (462,'mazowieckie','Warszawa','Lanciego',99,51,'63-430');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (463,'mazowieckie','Warszawa','Lanciego',29,82,'56-658');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (464,'mazowieckie','Warszawa','Lanciego',7,25,'87-783');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (465,'mazowieckie','Warszawa','Lanciego',45,1,'45-918');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (466,'mazowieckie','Warszawa','Lanciego',6,18,'51-288');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (467,'mazowieckie','Warszawa','Lanciego',98,96,'86-584');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (468,'mazowieckie','Warszawa','Lanciego',59,98,'09-005');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (469,'mazowieckie','Warszawa','Lanciego',5,87,'30-801');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (470,'mazowieckie','Warszawa','Lanciego',18,29,'02-121');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (471,'mazowieckie','Warszawa','Lanciego',62,84,'76-431');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (472,'mazowieckie','Warszawa','Lanciego',43,7,'46-275');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (473,'mazowieckie','Warszawa','Lanciego',1,23,'65-884');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (474,'mazowieckie','Warszawa','Lanciego',69,84,'71-599');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (475,'mazowieckie','Warszawa','Lanciego',80,14,'01-940');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (476,'mazowieckie','Warszawa','Lanciego',22,35,'23-705');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (477,'mazowieckie','Warszawa','Lanciego',95,38,'73-741');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (478,'mazowieckie','Warszawa','Lanciego',16,67,'89-218');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (479,'mazowieckie','Warszawa','Lanciego',50,6,'76-931');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (480,'mazowieckie','Warszawa','Lanciego',57,25,'29-946');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (481,'mazowieckie','Warszawa','Lanciego',74,45,'21-050');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (482,'mazowieckie','Warszawa','Lanciego',1,91,'81-778');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (483,'mazowieckie','Warszawa','Lanciego',47,25,'44-060');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (484,'mazowieckie','Warszawa','Lanciego',44,95,'89-515');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (485,'mazowieckie','Warszawa','Lanciego',87,75,'12-315');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (486,'mazowieckie','Warszawa','Lanciego',61,10,'20-221');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (487,'mazowieckie','Warszawa','Lanciego',19,72,'19-755');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (488,'mazowieckie','Warszawa','Lanciego',80,82,'47-695');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (489,'mazowieckie','Warszawa','Lanciego',73,70,'96-696');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (490,'mazowieckie','Warszawa','Lanciego',62,50,'19-032');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (491,'mazowieckie','Warszawa','Lanciego',37,29,'89-831');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (492,'mazowieckie','Warszawa','Lanciego',92,94,'91-121');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (493,'mazowieckie','Warszawa','Lanciego',49,14,'78-309');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (494,'mazowieckie','Warszawa','Lanciego',56,70,'02-544');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (495,'mazowieckie','Warszawa','Lanciego',5,65,'66-235');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (496,'mazowieckie','Warszawa','Lanciego',57,12,'52-107');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (497,'mazowieckie','Warszawa','Lanciego',34,87,'66-028');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (498,'mazowieckie','Warszawa','Lanciego',16,57,'38-774');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (499,'mazowieckie','Warszawa','Lanciego',85,54,'77-703');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (500,'mazowieckie','Warszawa','Lanciego',89,47,'78-781');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (501,'mazowieckie','Warszawa','Lanciego',94,53,'88-482');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (502,'mazowieckie','Warszawa','Lanciego',30,94,'32-276');
INSERT INTO Address(id,province,city,street,buildingNumber,flatNumber,zipCode) VALUES (503,'mazowieckie','Warszawa','Lanciego',75,73,'46-809');
SET IDENTITY_INSERT Address OFF;
