SET IDENTITY_INSERT Teacher ON;
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (1,'Piotr','Nowak','1990-01-18','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (2,'Piotr','Kowalski','1983-12-27','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (3,'Piotr','Wiśniewski','1984-03-01','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (4,'Piotr','Wójcik','1990-01-28','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (5,'Piotr','Kowalczyk','1981-03-01','male','dr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (6,'Piotr','Kamiński','1987-05-11','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (7,'Paweł','Nowak','1988-06-03','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (8,'Paweł','Kowalski','1987-05-21','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (9,'Paweł','Wiśniewski','1983-01-11','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (10,'Paweł','Wójcik','1981-06-19','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (11,'Paweł','Kowalczyk','1984-04-12','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (12,'Paweł','Kamiński','1980-12-21','male','dr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (13,'Adam','Nowak','1989-01-06','male','dr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (14,'Adam','Kowalski','1981-07-24','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (15,'Adam','Wiśniewski','1989-11-28','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (16,'Adam','Wójcik','1985-04-30','male','dr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (17,'Adam','Kowalczyk','1986-02-24','male','dr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (18,'Adam','Kamiński','1981-04-25','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (19,'Zbigniew','Nowak','1988-03-16','male','dr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (20,'Zbigniew','Kowalski','1980-08-20','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (21,'Zbigniew','Wiśniewski','1988-02-26','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (22,'Zbigniew','Wójcik','1988-09-10','male','dr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (23,'Zbigniew','Kowalczyk','1982-06-26','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (24,'Zbigniew','Kamiński','1990-03-09','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (25,'Jan','Nowak','1987-10-15','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (26,'Jan','Kowalski','1989-03-06','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (27,'Jan','Wiśniewski','1980-11-06','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (28,'Jan','Wójcik','1982-12-01','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (29,'Jan','Kowalczyk','1983-04-16','male','mgr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (30,'Jan','Kamiński','1982-09-13','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (31,'Kamil','Nowak','1987-09-13','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (32,'Kamil','Kowalski','1990-01-26','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (33,'Kamil','Wiśniewski','1983-04-28','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (34,'Kamil','Wójcik','1983-02-20','male','mgr');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (35,'Kamil','Kowalczyk','1980-01-07','male','dr inż.');
INSERT INTO Teacher(id,firstName,lastName,birthDate,sex,degree) VALUES (36,'Kamil','Kamiński','1986-11-08','male','mgr');
SET IDENTITY_INSERT Teacher OFF;
