INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 1), (SELECT $node_id FROM [Group] WHERE id = 22), 'Ekonomia', 14);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 1), (SELECT $node_id FROM [Group] WHERE id = 26), 'Ekonomia', 30);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 1), (SELECT $node_id FROM [Group] WHERE id = 35), 'Ekonomia', 30);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 2), (SELECT $node_id FROM [Group] WHERE id = 25), 'Etyka', 10);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 2), (SELECT $node_id FROM [Group] WHERE id = 32), 'Etyka', 16);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 3), (SELECT $node_id FROM [Group] WHERE id = 21), 'Filozofia', 14);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 3), (SELECT $node_id FROM [Group] WHERE id = 0), 'Filozofia', 24);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 4), (SELECT $node_id FROM [Group] WHERE id = 10), 'Fizyka', 56);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 4), (SELECT $node_id FROM [Group] WHERE id = 4), 'Fizyka', 54);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 5), (SELECT $node_id FROM [Group] WHERE id = 17), 'Analiza matematyczna', 54);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 5), (SELECT $node_id FROM [Group] WHERE id = 22), 'Analiza matematyczna', 52);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 5), (SELECT $node_id FROM [Group] WHERE id = 16), 'Analiza matematyczna', 40);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 6), (SELECT $node_id FROM [Group] WHERE id = 24), 'Fizyka', 18);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 6), (SELECT $node_id FROM [Group] WHERE id = 23), 'Fizyka', 52);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 7), (SELECT $node_id FROM [Group] WHERE id = 2), 'Ekonomia', 16);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 7), (SELECT $node_id FROM [Group] WHERE id = 10), 'Ekonomia', 54);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 8), (SELECT $node_id FROM [Group] WHERE id = 3), 'Fizyka', 28);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 8), (SELECT $node_id FROM [Group] WHERE id = 12), 'Fizyka', 56);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 8), (SELECT $node_id FROM [Group] WHERE id = 19), 'Fizyka', 20);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 9), (SELECT $node_id FROM [Group] WHERE id = 7), 'Fizyka', 34);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 9), (SELECT $node_id FROM [Group] WHERE id = 22), 'Fizyka', 24);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 10), (SELECT $node_id FROM [Group] WHERE id = 5), 'Filozofia', 60);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 10), (SELECT $node_id FROM [Group] WHERE id = 30), 'Filozofia', 48);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 11), (SELECT $node_id FROM [Group] WHERE id = 33), 'Ekonomia', 42);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 11), (SELECT $node_id FROM [Group] WHERE id = 21), 'Ekonomia', 34);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 11), (SELECT $node_id FROM [Group] WHERE id = 17), 'Ekonomia', 52);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 12), (SELECT $node_id FROM [Group] WHERE id = 34), 'Filozofia', 12);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 12), (SELECT $node_id FROM [Group] WHERE id = 20), 'Filozofia', 42);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 12), (SELECT $node_id FROM [Group] WHERE id = 31), 'Filozofia', 10);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 13), (SELECT $node_id FROM [Group] WHERE id = 1), 'Fizyka', 24);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 13), (SELECT $node_id FROM [Group] WHERE id = 18), 'Fizyka', 34);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 13), (SELECT $node_id FROM [Group] WHERE id = 15), 'Fizyka', 56);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 14), (SELECT $node_id FROM [Group] WHERE id = 7), 'Analiza matematyczna', 14);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 14), (SELECT $node_id FROM [Group] WHERE id = 6), 'Analiza matematyczna', 42);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 15), (SELECT $node_id FROM [Group] WHERE id = 35), 'Filozofia', 44);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 16), (SELECT $node_id FROM [Group] WHERE id = 21), 'Filozofia', 46);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 17), (SELECT $node_id FROM [Group] WHERE id = 5), 'Filozofia', 56);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 17), (SELECT $node_id FROM [Group] WHERE id = 31), 'Filozofia', 48);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 17), (SELECT $node_id FROM [Group] WHERE id = 27), 'Filozofia', 12);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 18), (SELECT $node_id FROM [Group] WHERE id = 14), 'Ekonomia', 24);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 18), (SELECT $node_id FROM [Group] WHERE id = 26), 'Ekonomia', 12);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 18), (SELECT $node_id FROM [Group] WHERE id = 26), 'Ekonomia', 20);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 19), (SELECT $node_id FROM [Group] WHERE id = 21), 'Fizyka', 38);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 19), (SELECT $node_id FROM [Group] WHERE id = 25), 'Fizyka', 50);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 20), (SELECT $node_id FROM [Group] WHERE id = 2), 'Filozofia', 40);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 20), (SELECT $node_id FROM [Group] WHERE id = 28), 'Filozofia', 14);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 20), (SELECT $node_id FROM [Group] WHERE id = 24), 'Filozofia', 18);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 21), (SELECT $node_id FROM [Group] WHERE id = 6), 'Filozofia', 30);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 21), (SELECT $node_id FROM [Group] WHERE id = 17), 'Filozofia', 46);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 22), (SELECT $node_id FROM [Group] WHERE id = 22), 'Etyka', 10);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 22), (SELECT $node_id FROM [Group] WHERE id = 28), 'Etyka', 18);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 22), (SELECT $node_id FROM [Group] WHERE id = 23), 'Etyka', 34);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 23), (SELECT $node_id FROM [Group] WHERE id = 19), 'Ekonomia', 36);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 23), (SELECT $node_id FROM [Group] WHERE id = 7), 'Ekonomia', 28);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 24), (SELECT $node_id FROM [Group] WHERE id = 32), 'Fizyka', 10);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 25), (SELECT $node_id FROM [Group] WHERE id = 35), 'Analiza matematyczna', 48);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 26), (SELECT $node_id FROM [Group] WHERE id = 8), 'Ekonomia', 42);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 27), (SELECT $node_id FROM [Group] WHERE id = 3), 'Analiza matematyczna', 42);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 28), (SELECT $node_id FROM [Group] WHERE id = 22), 'Ekonomia', 20);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 29), (SELECT $node_id FROM [Group] WHERE id = 29), 'Etyka', 56);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 30), (SELECT $node_id FROM [Group] WHERE id = 34), 'Analiza matematyczna', 28);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 30), (SELECT $node_id FROM [Group] WHERE id = 16), 'Analiza matematyczna', 48);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 31), (SELECT $node_id FROM [Group] WHERE id = 22), 'Analiza matematyczna', 54);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 31), (SELECT $node_id FROM [Group] WHERE id = 2), 'Analiza matematyczna', 44);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 32), (SELECT $node_id FROM [Group] WHERE id = 31), 'Etyka', 30);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 32), (SELECT $node_id FROM [Group] WHERE id = 35), 'Etyka', 18);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 32), (SELECT $node_id FROM [Group] WHERE id = 20), 'Etyka', 28);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 33), (SELECT $node_id FROM [Group] WHERE id = 34), 'Analiza matematyczna', 22);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 33), (SELECT $node_id FROM [Group] WHERE id = 5), 'Analiza matematyczna', 16);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 33), (SELECT $node_id FROM [Group] WHERE id = 7), 'Analiza matematyczna', 28);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 34), (SELECT $node_id FROM [Group] WHERE id = 0), 'Ekonomia', 24);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 35), (SELECT $node_id FROM [Group] WHERE id = 17), 'Ekonomia', 54);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 35), (SELECT $node_id FROM [Group] WHERE id = 1), 'Ekonomia', 36);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 35), (SELECT $node_id FROM [Group] WHERE id = 32), 'Ekonomia', 18);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 36), (SELECT $node_id FROM [Group] WHERE id = 12), 'Filozofia', 44);
INSERT INTO teaches ($from_id, $to_id, subject, hours) VALUES ((SELECT $node_id FROM Teacher WHERE id = 36), (SELECT $node_id FROM [Group] WHERE id = 4), 'Filozofia', 42);
